name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-qingdao.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/linuxserver/qbittorrent:amd64-4.1.9.99201911190849-6738-0b055d8ubuntu18.04.1-ls54 docker://registry.cn-qingdao.aliyuncs.com/lentudent/qbittorrent:amd64-4.1.9.99201911190849-6738-0b055d8ubuntu18.04.1-ls54
         
         
         
